### ISSUE TITLE
vue.runtime.esm.js?2b0e:619 [Vue warn]: Error in callback for watcher "currentTab": "TypeError: Cannot read property '0' of undefined"

### ISSUE THREAD

**Issue by heshamelmasry77** [karambafe/vue-tabs-with-active-line#10]
hello i get this bug :

``` Error in callback for watcher "currentTab": "TypeError: Cannot read property '0' of undefined" ```

**Comment by karambafe** [comment]
Hey.
Can you describe a case when an error occurs?
Or attach a link to codesanbox?

**Comment by heshamelmasry77** [comment]
i have fixed it.  the issue was when you use the tabs more than two times with same current tab variable
