### ISSUE TITLE
how to add i18n?

### ISSUE THREAD

**Issue by yiyasha15** [karambafe/vue-tabs-with-active-line#32]
i'm currently using this plugins, and want to implement i18n. i can change the content of the tab but how do i change the 'tab title" in data function?

**Comment by karambafe** [comment]
Hi!
You can use computed properties instead of the data for tabs array:

```
data: () => ({
  currentTab: 'tab1',
}),
computed: {
  tabs() {
     return [
        { title: this.$t('key1'), value: 'tab1' },
        { title: this.$t('key2'), value: 'tab2' },
     ];
  },
},

```
